apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: krapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-puma
  template:
    metadata:
      labels:
        app: rails-puma
    spec:
      containers:
        - name: krapp
          image: vinur/krapp:latest
          ports:
            - containerPort: 3000
